LOAD DATA INFILE 'data/artist.csv'
INTO TABLE artist
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(name);

LOAD DATA INFILE 'data/album.csv'
INTO TABLE album
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(name, releaseDate, albumCover);

LOAD DATA INFILE 'data/album_artist.csv'
INTO TABLE album_artist
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(albumID, artistID);

LOAD DATA INFILE 'data/song.csv'
INTO TABLE song
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(name, albumID, trackNumber, releaseDate, spotifyURL);

LOAD DATA INFILE 'data/song_artist.csv'
INTO TABLE song_artist
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(songID, artistID);

LOAD DATA INFILE 'data/user.csv'
INTO TABLE user
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(username, email, password, profilePicture, dateJoined);

LOAD DATA INFILE 'data/review.csv'
INTO TABLE review
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"' 
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(userID, songID, rating, comment, timestamp);
