DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS song_artist;
DROP TABLE IF EXISTS album_artist;
DROP TABLE IF EXISTS song;
DROP TABLE IF EXISTS album;
DROP TABLE IF EXISTS artist;
DROP TABLE IF EXISTS user;